name: Deploy FastAPI to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      # 1. Get latest code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Build Docker image
      - name: Build Docker image
        run: |
          docker-compose build --no-cache

      # 3. Start MySQL only for testing
      - name: Start MySQL
        run: |
          docker-compose up -d mysql

      # 4. Run tests 
      - name: Run tests
        run: |
          docker-compose run --rm fastapi pytest

      # 5. Stop test MySQL
      - name: Stop test containers
        if: always()
        run: |
          docker-compose down

      # 6. Deploy only if build + tests succeed
      - name: Deploy
        if: success()
        run: |
          cd ~/fastapi
          git fetch origin
          git reset --hard origin/main
          docker-compose build
          docker-compose up -d fastapi redis
          

      # 7. Check running containers
      - name: Check containers
        run: |
          docker-compose ps